### ISSUE TITLE
Add .gitignore file to visual studio solution folder

### ISSUE THREAD

**Issue by RowdyHowell** [zachhowell/toDoList#1]
Look into adding a ".gitignore" file to ignore some files in your repository.  This would ignore build files and more that aren't needed for the project.  The one below is recommended for Visual Studio projects.

https://github.com/github/gitignore/blob/master/VisualStudio.gitignore

**Comment by zachhowell** [comment]
Should be done, is it okay that there will be some ignored files that remain in the repo? Can't find a way to untrack all.
